CAN_CHI_DICT = {
    "Giáp Tý":    {"so": ["4", "9", "4"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp mệnh Thủy – vượng tài lộc"},
    "Ất Sửu":     {"so": ["5", "4", "9"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, đầu tư nhỏ sẽ gặp may"},
    "Bính Dần":   {"so": ["6", "2", "7"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, hợp tuổi Mộc – may mắn tình cảm"},
    "Đinh Mẹo":   {"so": ["7", "2", "7"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, mệnh Kim cẩn trọng quyết định"},
    "Mậu Thìn":   {"so": ["8", "3", "8"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, hợp tuổi Thủy – tài vận ổn"},
    "Kỷ Tỵ":      {"so": ["9", "8", "3"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, kinh doanh thuận lợi"},
    "Canh Ngọ":   {"so": ["0", "5", "0"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp tuổi Thổ – sức khỏe tốt"},
    "Tân Mùi":    {"so": ["1", "0", "5"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, đầu tư được lộc nhỏ"},
    "Nhâm Thân":  {"so": ["2", "9", "4"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, hợp tuổi Kim – dễ có tin vui"},
    "Quý Dậu":    {"so": ["3", "4", "9"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, phù hợp khởi sự nhỏ"},
    "Giáp Tuất":  {"so": ["4", "7", "2"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, làm việc cần sự kiên nhẫn"},
    "Ất Hợi":     {"so": ["5", "2", "7"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, hợp tuổi Mộc – quý nhân phù trợ"},
    "Bính Tý":    {"so": ["6", "1", "6"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, hạn chế đi xa"},
    "Đinh Sửu":   {"so": ["7", "6", "1"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, phù hợp làm thiện nguyện"},
    "Mậu Dần":    {"so": ["8", "5", "0"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, vượng tài vận – hợp tuổi Hỏa"},
    "Kỷ Mẹo":     {"so": ["9", "0", "5"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, nên chủ động công việc"},
    "Canh Thìn":  {"so": ["0", "9", "4"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp tuổi Thủy – làm ăn có lộc"},
    "Tân Tỵ":     {"so": ["1", "4", "9"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hạn chế tranh cãi"},
    "Nhâm Ngọ":   {"so": ["2", "3", "8"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, hợp tuổi Thủy – khởi đầu tốt đẹp"},
    "Quý Mùi":    {"so": ["3", "8", "3"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, đi xa gặp may"},
    "Giáp Thân":  {"so": ["4", "1", "6"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, mệnh Thủy dễ phát tài"},
    "Ất Dậu":     {"so": ["5", "6", "1"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, hợp tuổi Kim – có tin hỷ"},
    "Bính Tuất":  {"so": ["6", "5", "0"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, tránh nóng vội trong công việc"},
    "Đinh Hợi":   {"so": ["7", "0", "5"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, hợp tuổi Thổ – dễ phát triển"},
    "Mậu Tý":     {"so": ["8", "7", "2"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, kinh doanh thuận lợi"},
    "Kỷ Sửu":     {"so": ["9", "2", "7"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, giữ gìn sức khỏe"},
    "Canh Dần":   {"so": ["0", "3", "8"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, thuận lợi về nhà đất"},
    "Tân Mão":    {"so": ["1", "8", "3"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, hợp tuổi Kim – quý nhân trợ giúp"},
    "Nhâm Thìn":  {"so": ["2", "1", "6"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, thành công nhờ bạn bè"},
    "Quý Tỵ":     {"so": ["3", "6", "1"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp tuổi Thủy – tài lộc nhỏ"},
    "Giáp Ngọ":   {"so": ["4", "9", "4"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, sáng tạo được đề cao"},
    "Ất Mùi":     {"so": ["5", "4", "9"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, vượng về học hành"},
    "Bính Thân":  {"so": ["6", "2", "7"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, giao tiếp thuận lợi"},
    "Đinh Dậu":   {"so": ["7", "2", "7"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, hợp tuổi Kim – tiền bạc về"},
    "Mậu Tuất":   {"so": ["8", "3", "8"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, nhiều ý tưởng mới"},
    "Kỷ Hợi":     {"so": ["9", "8", "3"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, hợp tuổi Hỏa – đi xa có lộc"},
    "Canh Tý":    {"so": ["0", "5", "0"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, giữ gìn giấy tờ quan trọng"},
    "Tân Sửu":    {"so": ["1", "0", "5"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, đầu tư bất động sản hợp vận"},
    "Nhâm Dần":   {"so": ["2", "9", "4"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp tuổi Thủy – nhân duyên đến"},
    "Quý Mão":    {"so": ["3", "4", "9"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, dễ thăng tiến công việc"},
    "Giáp Thìn":  {"so": ["4", "7", "2"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, chủ động sẽ thành công"},
    "Ất Tỵ":      {"so": ["5", "2", "7"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, có lộc vãng lai"},
    "Bính Ngọ":   {"so": ["6", "1", "6"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, hòa khí sinh tài"},
    "Đinh Mùi":   {"so": ["7", "6", "1"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, quan hệ gia đình tốt"},
    "Mậu Thân":   {"so": ["8", "5", "0"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, có quý nhân giúp đỡ"},
    "Kỷ Dậu":     {"so": ["9", "0", "5"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, cẩn trọng giấy tờ xe cộ"},
    "Canh Tuất":  {"so": ["0", "9", "4"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, thuận lợi ký kết hợp đồng"},
    "Tân Hợi":    {"so": ["1", "4", "9"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp tuổi Thủy – ra ngoài gặp bạn cũ"},
    "Nhâm Tý":    {"so": ["2", "3", "8"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, tài chính ổn định"},
    "Quý Sửu":    {"so": ["3", "8", "3"],  "ngu_hanh": "Mộc",  "mo_ta": "Ngày Mộc, hợp tuổi Hỏa – sức khỏe dồi dào"},
    "Giáp Dần":   {"so": ["4", "1", "6"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, thuận lợi đầu tư nhỏ"},
    "Ất Mão":     {"so": ["5", "6", "1"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, nên dành thời gian nghỉ ngơi"},
    "Bính Thìn":  {"so": ["6", "5", "0"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, hợp tuổi Kim – cầu tài gặp may"},
    "Đinh Tỵ":    {"so": ["7", "0", "5"],  "ngu_hanh": "Hỏa",  "mo_ta": "Ngày Hỏa, dễ kết bạn mới"},
    "Mậu Ngọ":    {"so": ["8", "7", "2"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, đi lại cẩn trọng"},
    "Kỷ Mùi":     {"so": ["9", "2", "7"],  "ngu_hanh": "Thủy", "mo_ta": "Ngày Thủy, hợp tuổi Kim – chuyện nhỏ hóa lớn"},
    "Canh Thân":  {"so": ["0", "3", "8"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, nên tích cực chủ động"},
    "Tân Dậu":    {"so": ["1", "8", "3"],  "ngu_hanh": "Thổ",  "mo_ta": "Ngày Thổ, hợp tuổi Thủy – thuận lợi di chuyển"},
    "Nhâm Tuất":  {"so": ["2", "1", "6"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, kết giao nhiều bạn hữu"},
    "Quý Hợi":    {"so": ["3", "6", "1"],  "ngu_hanh": "Kim",  "mo_ta": "Ngày Kim, hợp tuổi Hỏa – tiền bạc dồi dào"},
}
